name: Demo Build

on:
  push:
    branches:
      - main
jobs:
  demo-build:
    name: Demo Build
    runs-on: windows-latest
    steps:
      - uses: goto-bus-stop/setup-zig@v2
      - name: Set Mingw64
        run: |
        #   (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
        #   7z x -aoa -oC:\ mingw64.7z ; rm mingw64.7z
      - name: Build
        run: |
          zig version
      # - name: Package Directories
      #   run: |
      #     cp -r C:\curl_install\lib C:\cpr_install -Force
      #     cp -r C:\curl_install\include C:\cpr_install -Force
      #     7z a cpr_MinGW64_Static.7z C:\cpr_install
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: cpr_MinGW64_Static
      #     path: cpr_MinGW64_Static.7z
      # - name: Update Cpr Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: cpr-build
      #     files: |
      #       cpr_MinGW64_Static.7z
