name: buzz Build

on:
  push:
    branches:
      - buzz
jobs:
  demo-build:
    name: buzz-language Build
    runs-on: windows-latest
    steps:
      - uses: goto-bus-stop/setup-zig@v2
      - name: Build
        run: |
          cd C:\ ; git clone --depth=1 https://github.com/buzz-language/buzz.git ; cd buzz
          git submodule update --init
          zig build -Doptimize=ReleaseSafe
      - name: Pack Packages
        run: |
          7z a buzz.7z C:\buzz\zig-out
      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          name: buzz
          path: buzz.7z
