name: libuv Build

on:
  push:
    branches:
      - libuv
jobs:
  libuv-build:
    name: libuv Build
    runs-on: windows-latest
    steps:
      - uses: goto-bus-stop/setup-zig@v2
      - name: Set Mingw64
        run: |
        #   (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
        #   7z x -aoa -oC:\ mingw64.7z ; rm mingw64.7z
      - name: Build
        run: |
          cd C:\ ; git clone --depth=1 https://github.com/libuv/libuv.git ; cd libuv
          curl --silent https://raw.githubusercontent.com/axojhf/zig_c_cxx_build/libuv/build.zig -o build.zig
          zig build
          ls
      - name: Pack Packages
        run: |
          7z a libuv_zig_static.7z C:\libuv\zig_out
      - uses: actions/upload-artifact@v3
        with:
          name: libuv_zig_static
          path: libuv_zig_static.7z
      # - name: Update Cpr Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: cpr-build
      #     files: |
      #       cpr_MinGW64_Static.7z
